services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: mcp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: code_analysis
      POSTGRES_USER: codeanalyzer
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-developmentpass}
      POSTGRES_INITDB_ARGS: "-c shared_preload_libraries=vector"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codeanalyzer -d code_analysis"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Database
      DATABASE_URL: postgresql+asyncpg://codeanalyzer:${POSTGRES_PASSWORD:-developmentpass}@postgres:5432/code_analysis
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: code_analysis
      POSTGRES_USER: codeanalyzer
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-developmentpass}

      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Server
      MCP_HOST: 0.0.0.0
      MCP_PORT: 8080
      MCP_LOGGING__LEVEL: ${MCP_LOGGING__LEVEL:-INFO}

      # Development
      DEBUG: ${DEBUG:-false}
      RELOAD: ${RELOAD:-false}

      # Enable all services
      ENABLE_SCANNER: ${ENABLE_SCANNER:-true}
      ENABLE_INDEXER: ${ENABLE_INDEXER:-true}
    volumes:
      - ./src:/app/src:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./code_to_analyze:/workspace:ro
      - repositories:/app/repositories
      - logs:/app/logs
      - embeddings_cache:/app/.embeddings_cache
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mcp-network
    command: all  # Run all services
    develop:
      watch:
        - action: restart
          path: ./src

  # Optional development tools
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mcp-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - mcp-network
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  repositories:
    driver: local
  logs:
    driver: local
  embeddings_cache:
    driver: local

networks:
  mcp-network:
    driver: bridge
